### ISSUE TITLE
Cardinal components needs to be updated

### ISSUE THREAD

**Issue by Sunconure11** [Arathain/charter#2]
It appears it might be causing a crash otherwise

**Comment by Arathain** [comment]
Will fix whenever I bother with a new update

**Comment by Sunconure11** [comment]
You might want to do so as soon as possible. I had been talking with the CC devs and 4.1.0 was causing weird oddities in workspaces and such because a dev was messing with experimental loom features

**Comment by TrulyS1r0** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Sunconure11** [comment]
Holy fucking shit one hell of a necro

**Comment by TrulyS1r0** [comment]
> Holy fucking shit one hell of a necro

Me?
